routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\CategorieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::match(['get', 'post'], '/panier/commander/save', [HomeController::class, "storeClientCommande"])->name('home.storeClientCommande');
Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/commander',[HomeController::class,"commander"])->name('home.commander');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::resource("categories",CategorieController::class);
Route::resource("admin",AdminController::class);
Route::get('/admin/search', [AdminController::class,'search'])->name('admin.search');
Route::get('/export-excel', [AdminController::class,'export'])->name('export');

resources/views/admin/edit.blade.php
@extends('layouts.admin')
@section('title','Ajouter une categorie')
@section('content')

<form action="{{route('admin.update', $commande->id)}}" method="POST">
    @csrf
    @method('PUT')
    <h3>Modification du commande N°{{ $commande->id }}</h3>
    <div class="form-group">
        <label class="mt-2" for="etat">Etat</label>
        <select   name="etat" class="form-control" id="etat">
          <option >{{ old('',$commande->etat)}}</option>
          <option >En attente de confirmation</option>
          <option >ِConfirmée</option>
          <option >Envoyé</option>
          <option >Payée</option>
          <option >Retournée</option>
        </select>
        <div class="form-group">
          <label for="prenom">Nom Complet</label>
          <input disabled type="text"  class="form-control" id="prenom" value="{{ old('',$commande->nom. " " . $commande->prenom) }}">
        </div>
        <div class="form-group">
          <label for="tele">Téléphone</label>
          <input disabled type="text" class="form-control" id="tele" value="{{ old('',$commande->tele) }}">
        </div>
        <div class="form-group">
          <label for="adresse">Adresse</label>
          <input disabled type="text" class="form-control" id="adresse" value="{{ old('',$commande->adresse) }}">
        </div>
        <div class="form-group">
          <label for="ville">Ville</label>
          <input disabled type="text" class="form-control" id="ville" value="{{ old('',$commande->ville) }}">
        </div>
        <div class="form-group">
            <label for="prix_total">Prix totale</label>
            <input disabled type="text" class="form-control mb-2" id="prix_total" value="{{ old('',$commande->prix_total) }}">
        </div>
    </div>
    <div>
        <input type="submit" class="btn btn-primary" value="Modifier">
    </div>
</form>


@endsection
{{-- <td>{{$commande->id}}</td>
<td>{{$commande->etat}}</td>
<td>{{$commande->prix_total}}</td>
<td>{{$commande->nom}}</td>
<td>{{$commande->prenom}}</td>
<td>{{$commande->tele}}</td>
<td>{{$commande->adresse}}</td>
<td>{{$commande->ville}}</td> --}}

resources/views/admin/index.blade.php
@extends('layouts.admin')
@section('title','List des commmands')
@section('content')

<h1 class="my-2">Recherche des commandes</h1>
<form method="GET" action="{{ route('admin.index') }}">
    <div class="input-group m-3">
       <div class="input-group-prepend">
         <span class="input-group-text rounded-0 border border-secondary" id="basic-addon3">Nom</span>
       </div>
       <input class="col-xs-5 border border-secondary  div-inputs" type="text" class="form-control" name="nom" id="nom" value="{{ old('',$nom) }}" aria-describedby="basic-addon3">
       <div class="input-group-prepend ">
        <span class="input-group-text rounded-0 border border-secondary" id="basic-addon3">Entre la date: </span>
       </div>
       <input class="col-xs-5 border border-secondary " type="date" class="form-control" name="first_date" id="first_date" value="" aria-describedby="basic-addon3">
       <div class="input-group-prepend ">
          <span class="input-group-text rounded-0 border border-secondary" id="basic-addon3">et: </span>
        </div>
        <input class="col-xs-5 border border-secondary div-inputs" type="date" class="form-control" name="second_date" id="second_date" value="" aria-describedby="basic-addon3">
        <div class="input-group-prepend">
          <span class="input-group-text rounded-0 border border-secondary" id="basic-addon3">Etat</span>
         </div>
         <select class="col-xs-5 border border-secondary  div-inputs" class="form-control" aria-describedby="basic-addon3" name="etat" id="etat">
           <option value="" selected>Selectione...</option>
           <option value="En attente de confirmation" >En attente de confirmation</option>
           <option value="ِConfirmée" >ِConfirmée</option>
           <option value="Envoyé" >Envoyé</option>
           <option value="Payée" >Payée</option>
           <option value="Retournée" >Retournée</option>
         </select>
         <button class="btn btn-primary mx-3" type="submit">Rechercher</button>
    </div>
</form>


<h1>Liste des categories</h1>
<div class="button">
    <a class="btn btn-primary" href="{{ route('export') }}">Export</a>
</div>
<table class="table mt-3">
  <tr>
    <th>ID</th>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Tele</th>
    <th>Adresse</th>
    <th>Ville</th>
    <th>Prix Totale</th>
    <th>Date du commande</th>
    <th>Etat</th>
    <th colspan="2">Actions</th>
  </tr>
  @forelse ($commandes as $commande)
      <tr>
        <td>{{$commande->id}}</td>
        <td>{{$commande->nom}}</td>
        <td>{{$commande->prenom}}</td>
        <td>{{$commande->tele}}</td>
        <td>{{$commande->adresse}}</td>
        <td>{{$commande->ville}}</td>
        <td>{{$commande->prix_total}}</td>
        <td>{{ \Carbon\Carbon::parse($commande->created_at)->format('m/d/Y') }}</td>
        <td>
            <span class ="@switch($commande->etat)
                @case('En attente de confirmation') confirmation @break
                @case('ِConfirmée') confirmed @break
                @case('Envoyé') sent @break
                @case('Payée') paid @break
                @case('Retournée') returned @break
                @default ''
                @endswitch">
                {{$commande->etat}}
            </span>
        </td>
        <td><a class="btn btn-secondary p-1" href="{{ route('admin.show',$commande->id) }}">Details</a></td>
        <td><a class="btn btn-success p-1" href="{{ route('admin.edit',$commande->id) }}">Modifier</a></td>
        {{-- <td>
            <form action="" method="POST">
                @method('DELETE')
                @csrf
                <input class="btn btn-danger p-1" type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer cette categorie?')">
        </form></td> --}}
        {{-- <td>{{$commande->client->nom}}</td>
        <td>{{$commande->client->prenom}}</td>
        <td>{{$commande->client->tele}}</td>
        <td>{{$commande->client->adresse}}</td>
        <td>{{$commande->client->ville}}</td> --}}
            @empty
            <td class="text-center" colspan="12">Aucun résultat trouvé.</td>
      </tr>
  @endforelse
</table>

@endsection

resources/views/admin/show.blade.php
@extends('layouts.admin')
@section('title','List des commmands')
@section('content')

<a class="btn btn-primary p-1 mb-3" href="{{route('admin.index')}}">Retourner vers la liste des commandes</a>
<h1>Detail du commande Num {{$commande->id}}</h1>
<div>
    <p><strong>Nom Complet:</strong> {{$commande->nom ." ". $commande->prenom}}</p>
    <p><strong>Téléphone:</strong> {{$commande->tele}}</p>
    <p><strong>Adresse:</strong> {{$commande->adresse}}</p>
    <p><strong>Ville:</strong> {{$commande->ville}}</p>
    <p><strong>Prix totale:</strong> {{$commande->prix_total}}</p>
    <p><strong>Date du commande:</strong> {{ \Carbon\Carbon::parse($commande->created_at)->format('m/d/Y') }}</p>
    <p><strong>Description:</strong></p>
     <ul>
        <li style="list-style-type: none">
            {!! $commande->description  !!}
        </li>
    </ul>
</div>

@endsection